
import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { useState } from "react";
import { Button } from "~/component/Button";
import { FormGroup } from "~/component/FormGroup";
import { Input } from "~/component/Input";
import { Quest } from "~/component/Quest";
import { Toggle } from "~/component/Toggle";
import { api } from "~/utils/api";



const GenerateTask: NextPage = () => {
  const [form, setForm] = useState({
      prompt: '',
  })
  const [quest, setQuest] = useState('')

  const generateQuest = api.generate.generateQuest.useMutation({
    onSuccess(data) {
      console.log('mutation finished', data)
      if (!data.returnedQuest) return;
      setQuest(data.returnedQuest)
    }
  })

  function updateForm(key: string) {
    return function(e: React.ChangeEvent<HTMLInputElement>) {
    setForm((prev) =>({
      ...prev, [key]: e.target.value,
    }));
      }
  }

  function handleFormSubmit(e: React.FormEvent) {
    e.preventDefault();
    // submit form data to backend
    generateQuest.mutate({
      prompt: form.prompt
    })
    setForm({prompt:''})
  }
    
  const session= useSession();

  const isLoggedIn = !!session.data;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="flex min-h-screen flex-col items-center justify-center">
        
        {!isLoggedIn && (
          <Button onClick={() => {
            signIn().catch(console.error)}}>
              Login
          </Button>
          )}
        {isLoggedIn && (
          <Button onClick={() => {
            signOut().catch(console.error)}}>
              Logout
          </Button>
          )}

            {session.data?.user.name}

        <form 
        className="flex flex-col gap-4"
        onSubmit={handleFormSubmit}
        >
          <FormGroup>
          <h1>new quest</h1>
          <Input placeholder='title' />
          <Input 
          placeholder='description'
          value={form.prompt}
          onChange={updateForm('prompt')}
          />
          <Toggle>Quest?</Toggle>
          <Button>
            Submit
          </Button>
          </FormGroup>

          <Quest className="w-[32rem]">
            {quest}
          </Quest>
        </form>
      </main>
    </>
  );
};

export default GenerateTask;

