import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { FormGroup } from "~/component/FormGroup";
import { Input } from "~/component/Input";



const GenerateTask: NextPage = () => {

    const [form, setForm] = useState({
        prompt: '',

    })


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
    <FormGroup>
    <span>new task</span>
    <Input onChange={(e) => 
        setForm((prev) =>({
            ...prev, prompt: e.target.value}))}
          />
    <button
    className="rounded bg-blue-400 px-4 py-2 hover:bg-blue-500"
    >submit</button>
    </FormGroup>
      </main>
    </>
  );
};

export default GenerateTask;

