import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>QuestLog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col">

      </main>
    </>
  );
};

export default Home;
