import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Button } from "~/component/Button";
import { Quest } from "~/component/Quest";
import { api } from "~/utils/api";
// import dayjs from "dayjs"

// dayjs().format()


interface Quest {
  id: string
  title: string
  description: string
  questTitle: string
  questDescription: string
}

const Home: NextPage = () => {
  const {data, isLoading: questsLoaded} = api.generate.getQuests.useQuery();
  console.log(data)

  return (
    <>
      <Head>
        <title>QuestLog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center mt-6 max-w-screen-md">

        <header className="justify-between flex items-end w-full border-b-2 border-slate-700 pb-2">
          <h1 className="text-3xl flex">Quests</h1>
          <Button className="flex align-text-bottom">Settings</Button>
        </header>

<ul className="">
  {data?.map((quest: Quest) => (
    <Quest 
      key={quest.id} 
      questTitle={quest.questTitle}
      questDescription={quest.questDescription}
      />
  ))}
</ul>



      </main>
    </>
  );
};

export default Home;
